### ISSUE TITLE
Cuando creo un documento me manda a un 404

### ISSUE THREAD

**Issue by jipster** [mxabierto/participa#106]
Pero luego si le doy refresh si se creo el doc. 

![image](https://cloud.githubusercontent.com/assets/5718530/8807083/a491bcac-2f9f-11e5-9091-82fc7b29ee63.png)

**Comment by codemoe** [comment]
Éste issue debió resolverse en el PR #119 

@jipster podrías revisarlo?

**Comment by urkonn** [comment]
@jipster hay que ir cerrando issues, hay tantos que no se puede saber qué ya se resolvió
