### ISSUE TITLE
A veces sale un 502 cuando quieres visualizar un doc

### ISSUE THREAD

**Issue by jipster** [mxabierto/participa#113]
![image](https://cloud.githubusercontent.com/assets/5718530/8807990/83e91530-2fa5-11e5-9c57-8cf4ecd54d3c.png)

**Comment by codemoe** [comment]
El error que se muestra en el screenshot sobre Elastic search ya no debería suceder a partir del merge del PR https://github.com/mxabierto/participa/pull/111

@jipster puedes revisar si esto sigue sucediendo o brindarme más información sobre el issue?

**Comment by codemoe** [comment]
@rodowi Como mencioné en el comentario anterior, El error que se muestra en el screenshot sobre Elastic search ya no debería suceder a partir del merge del PR #111

Creo que ya podríamos cerrar este issue
