### ISSUE TITLE
Necesitamos hardcodear un nuevo template para la consulta de SEGOB en Participa

### ISSUE THREAD

**Issue by jipster** [mxabierto/participa#114]
Deberían de ser un poco siguiendo cómo funciona hasta ahorita el de la Infraestructura Estratégica de Datos Abiertos - http://www.gob.mx/participa/docs/infraestructura-estrategica-de-datos-abiertos - 

![image](https://cloud.githubusercontent.com/assets/5718530/8813344/590ea2d0-2fc8-11e5-868b-db572a2bed03.png)

Específicamente tendríamos que poner un título a la sección de comentarios, similar a la de la Infraestructura Estratégica 

Idealmennte algo como en bold cambiar "Categorías de Datos Abiertos propuestos" por "Ejes propuestos"
Y en lugar de  "Vota por los conjuntos de datos que te interesan" poner " Da tu opinión y comienza la conversación" (https://cloud.githubusercontent.com/assets/5718530/8813294/ef501b26-2fc7-11e5-8d7e-5f4bbd9fcc71.png)

**Comment by rodowi** [comment]
ya no, dice @jipster
