### ISSUE TITLE
El link de Trámite en el navbar no funciona

### ISSUE THREAD

**Issue by rodowi** [mxabierto/participa#124]
"En el menu principal de www.gob.mx/participa al darle click a Trámite o Gobierno no hace ninguna acción, solo se muestra en el URL pero no dirige a ningún lado."

Así lo reporta el equipo de QA

**Comment by joecohens** [comment]
Esto debe de estar solucionado ya en la versión de QA ya que quitamos el router de Angular que estaba causando esos errores.

**Comment by urkonn** [comment]
Se había arreglado pero no me está funcionando otra vez en QA
