### ISSUE TITLE
Bug en QA al tratar de ver el detalle de un documento

### ISSUE THREAD

**Issue by rodowi** [mxabierto/participa#128]
![screen shot 2015-07-27 at 1 14 05 pm](https://cloud.githubusercontent.com/assets/705860/8913909/77c23db6-3461-11e5-88f2-8368163a09dd.png)

**Comment by rodowi** [comment]
Con otros sí funciona, p. ej. http://qa.participa.gob.mx/consulta/docs/documento-de-prueba-24jul2015

**Comment by codemoe** [comment]
Me parece que el error se debe a que por alguna razón ese documento no tiene un registro relacionado en la tabla doc_contents...

Se me hace raro porque el registro relacionado se crea en automático al crear un documento nuevo... no debería eliminarse....

@rodowi  Pueden probar agregar el registro relacionado en la tabla doc_contents a mano a ver si ese si es el problema.... y luego busquemos que pudo haber causado que se eliminara....

**Comment by urkonn** [comment]
ya no aparece el error pero ¿cómo se elige el layout?, son los de cofemer

**Comment by codemoe** [comment]
Para definir el layout se debe generar una categoría llamada cofemer en la db que tenga en la columna kind "layout" y asignarla al documento

<img width="192" alt="11807c44-30d7-11e5-9f24-ddcef653c0bc" src="https://cloud.githubusercontent.com/assets/4172905/8948748/eb120878-356f-11e5-8232-213b7fbc5f4f.png">

<img width="704" alt="25a537f0-30d7-11e5-82f0-47d99372745e" src="https://cloud.githubusercontent.com/assets/4172905/8948750/ecacc074-356f-11e5-92e0-bba297e50fdd.png">

**Comment by urkonn** [comment]
agregué la categoría pero no se muestra el layout, ¿de qué depende?

**Comment by rodowi** [comment]
hey @codemoe parece que el #132 lo resuelve

es porque los docs con ese layout no tienen contenido,

todo el texto lo metemos en el metadata intro_text!
