### ISSUE TITLE
Traducir opciones del navbar al español

### ISSUE THREAD

**Issue by rodowi** [mxabierto/participa#129]

**Comment by rodowi** [comment]
Es acá: https://github.com/mxabierto/participa/blob/a9f7834dd9d134b58925b6722bbef51836e649ee/resources/views/layouts/header.blade.php

**Comment by rodowi** [comment]
Después de #127, faltan aún las del menú y algunas del navbar

![screen shot 2015-07-28 at 5 40 27 pm](https://cloud.githubusercontent.com/assets/705860/8945749/d37ab838-354f-11e5-8069-602d4fa55ec1.png)

**Comment by urkonn** [comment]
lo cierra #127 

![selection_051](https://cloud.githubusercontent.com/assets/37691/8945876/0ae0672c-3551-11e5-8127-b2d5c7a54ff4.png)
