### ISSUE TITLE
No se muestra el layout de cofemer

### ISSUE THREAD

**Issue by urkonn** [mxabierto/participa#141]
![selection_061](https://cloud.githubusercontent.com/assets/37691/8999983/116a320a-3707-11e5-9184-279d1eb2a41c.png)

Debería verse así:
![selection_062](https://cloud.githubusercontent.com/assets/37691/8999969/f61d27be-3706-11e5-9bde-d76aa42c77df.png)

**Comment by rodowi** [comment]
En producción y staging se sigue viendo mal el layout
http://www.gob.mx/consulta/docs/SSA-292-237

**Comment by codemoe** [comment]
@rodowi 

Puedes revisar que en la DB de staging y en la de producción, en la tabla "categories" la categoría "cofemer" y la categoría "votos" digan en la columna kind "layout" en lugar de "category"?

**Comment by rodowi** [comment]
lo de la tabla lo está revisando @urkonn

**Comment by rodowi** [comment]
Este render debería funcionar: https://github.com/mxabierto/participa/blob/master/app/Http/Controllers/DocController.php#L88

**Comment by rodowi** [comment]
en staging, votos estaba en category, lo cambié a layout

**Comment by rodowi** [comment]
SAGARPA-11-34
tenía cofemer (1) de category, la 84 y 6 que es de SAGARPA, y le faltaba la 95 (que es cofemer layout)

![screen shot 2015-08-05 at 1 04 00 pm](https://cloud.githubusercontent.com/assets/705860/9093569/6ad2ce14-3b72-11e5-9146-49dcd47d21c3.png)

**Comment by rodowi** [comment]
tengo que hacer un UPDATE masivo, cool

**Comment by rodowi** [comment]
```sql
INSERT INTO category_doc (doc_id, category_id)
SELECT id as doc_id, 95 as category_id FROM docs WHERE created_at LIKE '2015-05-27%'
```

Donde 95 es (cofemer, layout)
Y el 27 de Mayo fue cuando hicimos el import masivo

**Comment by rodowi** [comment]
http://www.gob.mx/consulta/docs/SAGARPA-04-036
