### ISSUE TITLE
Que en móvil se ve una barra gris a la derecha

### ISSUE THREAD

**Issue by rodowi** [mxabierto/participa#149]
![screen shot 2015-07-31 at 08 37 52](https://cloud.githubusercontent.com/assets/705860/9015736/99766aae-3790-11e5-9f41-c9c24328655f.png)

será el scroll :trollface: ?

**Comment by chuckcfs** [comment]
es por el `<h1>` del banner, el `font-size` debe ser más chico en móvil

**Comment by chuckcfs** [comment]
una opción sería algo así:

en el html del banner:

```html
<h1 class="hidden-sm hidden-xs"><strong>gob<span class="red">.</span>mx/consulta</strong></h1>
<h1 class="text-small hidden-md hidden-lg"><strong>gob<span class="red">.</span>mx/consulta</strong></h1>
```

y en el css agregar una clase `text-small` o la que se le ponga en el `h1` y bajarle el `font-size`
