### ISSUE TITLE
Remover leyenda estática para producción.

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/participa#16]
<a href="https://github.com/rodowi"><img src="https://avatars.githubusercontent.com/u/705860?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rodowi](https://github.com/rodowi)**
_Fri Jan 23 17:35:47 2015_
_Originally opened as https://github.com/mxabierto/madison/issues/93_

----

ver #92

**Comment by rodowi** [comment]
Se quitó hace tiempo.
