### ISSUE TITLE
Como publisher puedo publicar un documento con el layout de leyes

### ISSUE THREAD

**Issue by rodowi** [mxabierto/participa#173]
El layout de leyes es una manera de subir un CSV que tiene snippets cambiados a una Ley grande. Como no queremos que el documento sea larguísimo (como las leyes), el publisher subirá sólo los párrafos modificados.

El truco está en que de cierta manera necesitaremos hacer referencia al doc original.

Wireframes pendientes...

**Comment by jipster** [comment]
Acá está la muestra de Secretaría de Economía para empezar el layout

**Comment by rodowi** [comment]
### Algunas librerías que encontré

http://ejohn.org/projects/javascript-diff-algorithm/

![screen shot 2015-08-17 at 7 12 21 pm](https://cloud.githubusercontent.com/assets/705860/9319417/ea5703ee-4513-11e5-8e4d-63b6e2393c3c.png)

------

https://code.google.com/p/google-diff-match-patch/

<img width="1022" alt="screen shot 2015-08-17 at 7 14 54 pm" src="https://cloud.githubusercontent.com/assets/705860/9319465/4493211c-4514-11e5-85e0-40949e7cd26e.png">

------

https://github.com/wickedest/Mergely

![screen shot 2015-08-17 at 7 11 54 pm](https://cloud.githubusercontent.com/assets/705860/9319411/d87f63a0-4513-11e5-8bc2-85d4e7438abc.png)

------

https://github.com/cemerick/jsdifflib

![screen shot 2015-08-17 at 7 13 25 pm](https://cloud.githubusercontent.com/assets/705860/9319440/0ed45a14-4514-11e5-831d-3096c3097d01.png)

**Comment by rodowi** [comment]
Mockups: https://moqups.com/rwilhelmy@gmail.com/rPtt4aE6/p:a1782c69a

**Comment by rodowi** [comment]
Se me ocurre que la propuesta del schema del CSV que subirían por documento sería algo como esto:

Etiqueta  | Actual | Propuesta
------------ | -------- | -------------
Modificación al código 0301.93.01 del capítulo 3  | Carpas (Cyprinus carpio, Carassius carassius, Ctenopharyngodon idellus, Hypophthalmichthys spp., Cirrhinus spp., Mylopharyngodon piceus). | Carpas (Cyprinus spp., Carassius spp., Ctenopharyngodon idellus, Hypophthalmichthys spp., Cirrhinus spp., Mylopharyngodon piceus).
Anexo al código 0301.93.04 del capítulo 3 | | Hígados, huevas, lechas, aletas, cabezas, colas, vejigas natatorias y demás despojos comestibles de pescado:

**Comment by jipster** [comment]
Acá está el total de cambios propuestos por SE para LIGIE https://docs.google.com/spreadsheets/d/1Z7kaRZIUGkI9j29pmtJmm2gHDx5rdjLLtjpOS2DWdPI/edit?usp=sharing

**Comment by rodowi** [comment]
Será mucho trabajo sacar la info de los comentarios @jipster 

Porfa sigan el formato propuesto con columnas por ediciones

**Comment by jipster** [comment]
Aquí está cada uno de los cambios hasta ahora propuestos por SE. Esto sería lo que se publicaría: https://docs.google.com/spreadsheets/d/12BnK1P8-tIY0A2_htPaep_w3o_JPpaMzOf02UX7C56M/edit?usp=sharing

**Comment by codemoe** [comment]
@jipster Ese último formato creo que no funciona porque no está comparando nada con nada.... no hay un antes y después....

Necesitamos usar un formato mas parecido al que @rodowi mencionó antes... Además de que será más sencillo de procesar y de mostrar...

**Comment by jipster** [comment]
@codemoe el lunes les doy el formato final con estas características

**Comment by jipster** [comment]
@codemoe @rodowi chequen este capítulo, con este quedaría bien el lado a lado? https://docs.google.com/spreadsheets/d/1TkWQJmdUMxcuOgtmAJbmPd3bgFrVugsk-3wErVuXAaY/edit?usp=sharing

**Comment by rodowi** [comment]
Dentro del PR #190 quedan algunas cosas pendientes mencionadas en los comentarios.
