### ISSUE TITLE
Integrar comscore analytics

### ISSUE THREAD

**Issue by rodowi** [mxabierto/participa#187]

**Comment by jipster** [comment]
@rodowi esto quedaría esta semana?

**Comment by urkonn** [comment]
Falta la medición de las interacciones:

- [ ] Botones de votación "A favor/En contra" de documentos.

- [ ] Campos de comentarios

- [ ] Votación en comentarios y flagging 
![selection_080](https://cloud.githubusercontent.com/assets/37691/10180035/9096116e-66cf-11e5-8e7b-e559b0c1a19f.png)

No funcionó llamar a la función en el controlador https://github.com/mxabierto/participa/blob/master/resources/assets/js/controllers/Reader.js#L74-L75

**Comment by chuckcfs** [comment]
@rodowi @urkonn falta el `gulp build` los cambios pasados no entraron al build, esta llamada https://github.com/mxabierto/participa/blob/master/resources/assets/js/controllers/Reader.js#L74-L75 no está en producción

<img width="599" alt="screen shot 2015-09-30 at 12 57 33" src="https://cloud.githubusercontent.com/assets/1383865/10201674/d6bfe126-6772-11e5-9374-49c4240510f3.png">

debería ser

<img width="1112" alt="screen shot 2015-09-30 at 12 57 54" src="https://cloud.githubusercontent.com/assets/1383865/10201695/e8493550-6772-11e5-829f-5e13b8773b4d.png">

**Comment by rodowi** [comment]
![screen shot 2015-09-30 at 1 57 24 pm](https://cloud.githubusercontent.com/assets/705860/10203410/69029576-677b-11e5-8b57-3be5f41547a4.png)
![screen shot 2015-09-30 at 1 56 57 pm](https://cloud.githubusercontent.com/assets/705860/10203411/691b13f8-677b-11e5-9f62-03ca5a9727ed.png)
