### ISSUE TITLE
Importar masivamente los documentos con el layout Leyes

### ISSUE THREAD

**Issue by urkonn** [mxabierto/participa#191]
Se debe poder importar masivamente capítulos como documentos

**Comment by jipster** [comment]
Además importar masivamente las descripciones junto con el contenido de los documentos

**Comment by jipster** [comment]
@rodowi tu nos avisas de esto tanto para el contenido de descripción como del contenido del doc a comentar.

**Comment by rodowi** [comment]
atendiéndose en https://github.com/mxabierto/tepatitlan/pull/27

**Comment by rodowi** [comment]
Se va a producción hasta después del 2 OCT
