### ISSUE TITLE
En el layout Leyes no se requiere tener "Contenidos"

### ISSUE THREAD

**Issue by jipster** [mxabierto/participa#192]

**Comment by codemoe** [comment]
@jipster o @urkonn podrían detallar el issue.... no me quedó claro a qué se refieren....

**Comment by urkonn** [comment]
@jipster se refiere a esta sección 

![selection_076](https://cloud.githubusercontent.com/assets/37691/9949908/aeabe0fc-5d79-11e5-93ad-40d7724d5586.png)

**Comment by codemoe** [comment]
@urkonn @jipster 

https://github.com/mxabierto/participa/pull/194

Listo!

**Comment by urkonn** [comment]
@codemoe la sección **Contenidos** ya no aparece en los otros layouts

**Comment by codemoe** [comment]
@urkonn Únicamente se eliminó la tabla de contenidos del layout de leyes. En los demás layouts se quedó tal cual como estaba.

Yo aún veo la sección Contenidos en los demás layouts...

![captura de pantalla 2015-09-18 a las 12 07 39](https://cloud.githubusercontent.com/assets/4172905/9965745/ff5062ba-5dfd-11e5-95fa-26278434e8b1.png)


Considera que para que aparezca la sección Contenidos es necesario que el contenido del documento tenga encabezados h2 o ##

**Comment by jipster** [comment]
@codemoe está perfecto, sólo el layout de leyes en este caso necesitas que se elimine.

**Comment by codemoe** [comment]
@jipster El PR #194 es justo lo que hace, elimina la sección Contenido únicamente del layout de leyes además del fix del título de la pestaña
