### ISSUE TITLE
[Code] - (1) Avoid non-neutralized user-controlled input to be part of a pathname (file or directory) used in I/O operations

### ISSUE THREAD

**Issue by rodowi** [mxabierto/participa#198]
**Lo que me reportan:**

El software usa la entrada externa para la construcción de una ruta que pretende identificar un archivo o directorio que se encuentra debajo de un directorio padre restringido, pero no neutraliza adecuadamente elementos especiales dentro de la ruta de acceso que pueden causar que el nombre de ruta resuelva a un lugar fuera de la directorio restringido.

Si la configuración del servidor web / php.ini no restringe el acceso a los archivos fuera de ciertos directorios restringidos, el atacante puede recuperar archivos sensibles, y si el archivo está escrito con contenidos controlados por entradas del usuario, el atacante puede cambiar los archivos de configuración (como .htaccess entre otros), contenidos web o bibliotecas). El acceso a los archivos del sistema (/ etc / password habitual en sistemas Unix / Linux) también se podría permitir lo cual será fatal para el servicio.

Se detectó esto en el archivo perteneciente al framework Laravel el cual no es algo que fue construido para la aplicación. La severidad depende de la función de server.php en el aplicativo.

Ejemplo de uso incorrecto:
```php
<?php
// path is a supposedly 'hidden field' received, indicating the path to dump,
// but potential attacker has full control on the HTTP message received by the application
$path = $_GET['path'];
// Vulnerable: attacker could possibly dump PHP source code, sensitive files (like /etc/password), etc.
readfile($path);
?>
```
Ejemplo uso recomendado:
```php
<?php
// Ensure at least that target file cannot be out of a given directory (unless attacker creates links by other means)
$path = MY_BASEDIR . basename(realpath($_GET['path']));
// FIXED (attacker may control filename but not the directory containing file to read)
readfile($path);
?>
```
Archivo server.php
Línea 15  
        [source user_input (array _SERVER)], line 9: 
$uri = urldecode(
    parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH)
)

[sink path_traversal (function file_exists)], line 15: 
$uri !== '/' and file_exists(__DIR__.'/public'.$uri)

**Comment by codemoe** [comment]
@rodowi 

Técnicamente el uso del input en el archivo server.php de Laravel se parace al uso recomendado ya que a pesar de que si obtiene el path del "user input", valida específicamente si el archivo existe dentro del directorio public evitando acceso a archivos ocultos o privados que se encuentran fuera del directorio public/

@joecohens qué opinas?
