### ISSUE TITLE
Usar Redis para sesiones de usuario

### ISSUE THREAD

**Issue by rodowi** [mxabierto/participa#204]
Con esto buscamos solventar el problema con el Load Balancer

**Comment by rodowi** [comment]
Relacionado con el #184

**Comment by joecohens** [comment]
Excelente! Lo que necesitamos para que esto pase es:

1) Crear una instancia de redis.
2) Proporcionar credenciales para conectarnos.
3) Configurar Laravel para que use redis para las sesiones. 

/cc @rodowi @codemoe @urkonn 

Cualquier duda estoy pendiente.

**Comment by rodowi** [comment]
Basta con levantar el contenedor de Redis y que el código Laravel asuma los valores default de conexión a redis

Podemos usar https://github.com/mxabierto/dockerfile/blob/master/redis/Dockerfile

**Comment by rodowi** [comment]
```bash
docker build -t mxabierto/redis .
docker run --rm -it mxabierto/redis
```
