### ISSUE TITLE
Agregar evento Comscore sobre flagging de comentarios

### ISSUE THREAD

**Issue by rodowi** [mxabierto/participa#207]

**Comment by rodowi** [comment]
Pista: https://github.com/mxabierto/participa/blob/e11584b1f28f2c4312353dda5079c634f7fe73ef/resources/assets/js/controllers/Reader.js

**Comment by urkonn** [comment]
https://github.com/mxabierto/participa/blob/master/resources/assets/js/controllers/Comment.js#L200

**Comment by rodowi** [comment]
es en annotator-madison:addFlag
