### ISSUE TITLE
¿Podemos agregar versiones o timestamps como parte del query string de los API endpoints?

### ISSUE THREAD

**Issue by urkonn** [mxabierto/participa#239]
@joecohens @codemoe 
Vamos a utilizar un CDN y queremos saber si es posible agregar alguna etiqueta que indique que el endpoint ha cambiado para actualizar el cache, algo como esto: 

```
api/docs/31337/comments.json?20150910123456
```

¿es posible? ¿es buena práctica?

**Comment by codemoe** [comment]
@urkonn 

Si es posible agregar una etiqueta al endpoint para hacer que omita el cache. Esa etiqueta probablemente debe ser el timestamp al momento de hacer la petición. Consideremos que eso anula por completo las ventajas del CDN para ese endpoint (Que para los comments probablemente es correcto hacerlo).

Generar una etiqueta nueva únicamente cuando algo ha cambiado y utilizar la misma etiqueta hasta el siguiente cambio es una implementación bastante más compleja ya que implica tener un lugar donde almacenar la etiqueta actual, actualizarla en cada cambio y traerla en cada ocasión que se llama al endpoint lo que puede resultar en más problemas de performance que solo ignorar el CDN agregando el timestamp así que probablemente esa sea una mejor forma.

**Comment by urkonn** [comment]
Gracias @codemoe 

cc @rodowi
