### ISSUE TITLE
[Code] - (4) Never use JavaScript 'history' object or navigation-based positioning functions.

### ISSUE THREAD

**Issue by rodowi** [mxabierto/participa#249]
Existe la vulnerabilidad de posicionamiento basados en navegación. Esta norma identifica cualquier uso del objeto ' history ' o funciones de posicionamiento.
	Se considera mala práctica por las siguientes razones:

o	POST: Si una página visitada se generó con POST, el navegador emitirá una advertencia si los datos presentados no están codificados en la URL. 
o	PRIVACIDAD: Ninguna aplicación debe saber qué páginas visitó un usuario (Los navegadores emitirán una alerta de seguridad y bloquearán el acceso) 
o	LÓGICA DE NAVEGACIÓN POBRES: La secuencia de página exacta tomada por usuarios puede no coincidir con las   expectativas del programador. 
    	
Como ejemplo, lo siguiente se considera violación:
window.back ();                         // VIOLATION
self.history.go (-1);                   // VIOLATION

Y las mejores prácticas de este ejemplo indican que la forma correcta sería:
window.location.replace (targetUrl);    // OK, not using navigate
Donde targetUrl es una URL exacta.

Es mucho mejor para colocar al usuario en la URL exacta (usando ‘location’ validando siempre la información que se recibe con esta funcion), esto permite al usuario jugar con los botones de navegación del explorador si lo necesita. Se requiere saber sobre que se está haciendo posterior a ésta condición y si es necesaria tenerla ya que la norma identifica como vulnerabilidad cualquier uso del objeto ' history’.

Archivo public/build/dist/js/libs-232da6ed.js
Línea 25000  
              history = window.history,

Archivo public/build/dist/js/libs-232da6ed.js
Línea 25122  
            if (history !== window.history) history = window.history;

Archivo public/build/dist/js/libs-232da6ed.js
Línea 25134  
                if (replace) history.replaceState(null, '', url);

Archivo public/build/dist/js/libs-232da6ed.js
Línea 25136  
                  history.pushState(null, '', url);

**Comment by codemoe** [comment]
@rodowi Éste issue hace referencia a código core de Angular encargado de actualizar los URLs al momento de navegar en el sitio, no creo que sea posible hacer ningún cambio ni creo que sea un issue ya que Angular no lo usa para enviar al usuario hacia atrás en la navegación...
