### ISSUE TITLE
Document saved, but there was an error with Elasticsearch: couldn't connect to host

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/participa#25]
<a href="https://github.com/rodowi"><img src="https://avatars.githubusercontent.com/u/705860?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rodowi](https://github.com/rodowi)**
_Fri Feb 13 00:44:27 2015_
_Originally opened as https://github.com/mxabierto/madison/issues/113_

----

ver https://github.com/opengovfoundation/madison/issues/496

**Comment by carlosmaya** [comment]
<a href="https://github.com/rodowi"><img src="https://avatars.githubusercontent.com/u/705860?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rodowi](https://github.com/rodowi)**
_Fri Feb 13 01:03:00 2015_

----

Parece que no es crítico. El app sigue funcionando.

**Comment by carlosmaya** [comment]
<a href="https://github.com/rodowi"><img src="https://avatars.githubusercontent.com/u/705860?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [rodowi](https://github.com/rodowi)**
_Wed Mar 11 22:53:08 2015_

----

Relacionado: https://github.com/opengovfoundation/madison/issues/210

**Comment by codemoe** [comment]
@rodowi Me parece que éste issue ya está resuleto después de los últimos cambios y el PR #111

**Comment by rodowi** [comment]
parece que sí

veamos el ready queue en https://waffle.io/mxabierto/participa
