### ISSUE TITLE
Los documentos cerrados se ordenan después de los abiertos por default

### ISSUE THREAD

**Issue by rodowi** [mxabierto/participa#252]
En la lista de docs, los cerrados van hasta al final

**Comment by codemoe** [comment]
@rodowi no me queda claro el issue.... Cuando hicimos el cambio que permitía cerrar documentos se había solicitado que los cerrados se ordenaran después de los abiertos...

¿Queremos cambiar eso? o ¿Qué es el issue para revisar?

**Comment by rodowi** [comment]
El funcionamiento ya es así
