### ISSUE TITLE
Los botones de "A favor" y "En contra" no funcionan en ningún layout

### ISSUE THREAD

**Issue by jipster** [mxabierto/participa#255]

**Comment by codemoe** [comment]
@jipster @urkonn 

Buenas noches

Cómo nos pidieron, revisamos éste issue... Éste issue se resuelve en el PR #248. Específicamente con el cambio al archivo app/Http/Controllers/Api/UserController.php

Revisen por favor ese PR y en cuánto hagan merge debe quedar solucionado este issue

**Comment by urkonn** [comment]
gracias @codemoe :+1:
