### ISSUE TITLE
phpunit not running in vagrant machine

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/participa#26]
<a href="https://github.com/rodowi"><img src="https://avatars.githubusercontent.com/u/705860?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rodowi](https://github.com/rodowi)**
_Fri Feb 13 19:48:51 2015_
_Originally opened as https://github.com/mxabierto/madison/issues/118_

----

vagrant@precise64:/vagrant$ phpunit
PHP Warning:  require_once(PHP/CodeCoverage/Filter.php): failed to open stream: No such file or directory in /usr/bin/phpunit on line 38
PHP Fatal error:  require_once(): Failed opening required 'PHP/CodeCoverage/Filter.php' (include_path='.:/usr/local/zend/share/ZendFramework/library:/usr/local/zend/share/pear') in /usr/bin/phpunit on line 38

**Comment by rodowi** [comment]
ya no nos importa vagrant
