### ISSUE TITLE
No se actualizan los archivos al hacer el build con gulp

### ISSUE THREAD

**Issue by urkonn** [mxabierto/participa#260]
@codemoe
hicimos el siguiente cambio https://github.com/mxabierto/participa/pull/258
pero nos faltó hacer el build, por alguna extraña razón no podemos actualizarlo

 ¿nos podrías ayudar?

**Comment by codemoe** [comment]
@urkonn 

En el commit https://github.com/mxabierto/participa/commit/1d2277c39eb809cdea621f40ff0b1b8ceeb3b1fb

hice un gulp y lo subí a tu branch de add-build-files

Para compilar usando gulp sólo hace falta correr el comando "gulp" sin agregados. Una de las razones por las que puede ocurrir un error al hacer "gulp" es la versión de node js con la que cuentan... Especíalmente si usan NVM es posible cambiar muy fácilmente de versión de node. 

yo uso node v0.12.7 en general pero para hacer build en participa siempre tengo que cambiar a la versión v0.10.33 para que no haya errores.... 

Espero que esto ayude....

**Comment by urkonn** [comment]
gracias @codemoe :+1:

**Comment by rodowi** [comment]
Estoy viendo que hay un #262, cerramos esto entonces @urkonn ?

**Comment by urkonn** [comment]
Si, hay que cerrarlo
