### ISSUE TITLE
Issues with nav drop-down for regular users

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/participa#34]
<a href="https://github.com/jipster"><img src="https://avatars.githubusercontent.com/u/5718530?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jipster](https://github.com/jipster)**
_Mon Feb 23 19:38:10 2015_
_Originally opened as https://github.com/mxabierto/madison/issues/155_

----

- [ ] Configuración de cuenta y gestión de grupos manda a una blank page
- [ ] Configuración de notificaciones manda a un blank page con navbar
- [ ] Adentro de Configuración de Notificaciones el dropdown se regresa a versión de no miembro

![screen shot 2015-02-23 at 12 46 08](https://cloud.githubusercontent.com/assets/5718530/6335391/da49de46-bb60-11e4-86aa-7a944eb6da74.png)
![screen shot 2015-02-23 at 13 34 51](https://cloud.githubusercontent.com/assets/5718530/6335388/da2fdf1e-bb60-11e4-8a75-bacee30f1516.png)
![screen shot 2015-02-23 at 13 34 40](https://cloud.githubusercontent.com/assets/5718530/6335389/da42d24a-bb60-11e4-80b2-734c9e927b81.png)
![screen shot 2015-02-23 at 13 32 33](https://cloud.githubusercontent.com/assets/5718530/6335390/da49d054-bb60-11e4-8e75-928d7f3cead8.png)

**Comment by codemoe** [comment]
@rodowi Me parece que éste issue ya está resuelto después de los últimos cambios

**Comment by rodowi** [comment]
ya lo validé yo
