### ISSUE TITLE
Revisar paleta de colores y corregir diferencias

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/participa#4]
<a href="https://github.com/rodowi"><img src="https://avatars.githubusercontent.com/u/705860?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rodowi](https://github.com/rodowi)**
_Tue Jan 13 02:20:41 2015_
_Originally opened as https://github.com/mxabierto/madison/issues/25_

----

Ver colores en https://github.com/mxabierto/madison/issues/18#issuecomment-69683771

**Comment by rodowi** [comment]
ya estamos importando el css directo de gob.mx
