### ISSUE TITLE
Mobile menu sucks big time

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/participa#5]
<a href="https://github.com/rodowi"><img src="https://avatars.githubusercontent.com/u/705860?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rodowi](https://github.com/rodowi)**
_Tue Jan 13 23:25:48 2015_
_Originally opened as https://github.com/mxabierto/madison/issues/33_

----

![screen shot 2015-01-13 at 5 24 51 pm](https://cloud.githubusercontent.com/assets/705860/5731452/29c57bac-9b49-11e4-8a74-4bc3e8e98910.png)

**Comment by rodowi** [comment]
![screen shot 2015-08-05 at 6 40 30 pm](https://cloud.githubusercontent.com/assets/705860/9100522/6a67fd6c-3ba1-11e5-9074-2de195082d0b.png)
