### ISSUE TITLE
El dropdown de categorías sólo muestra las de los 20 resultados

### ISSUE THREAD

**Issue by carlosmaya** [mxabierto/participa#63]
<a href="https://github.com/rodowi"><img src="https://avatars.githubusercontent.com/u/705860?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [rodowi](https://github.com/rodowi)**
_Fri May 29 02:14:26 2015_
_Originally opened as https://github.com/mxabierto/madison/issues/249_

----

**Comment by carlosmaya** [comment]
<a href="https://github.com/chuckcfs"><img src="https://avatars.githubusercontent.com/u/1383865?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chuckcfs](https://github.com/chuckcfs)**
_Fri May 29 02:18:24 2015_

----

a como esta ahorita es un filtro, hace sentido que sólo filtre los resultados en pantalla?

**Comment by carlosmaya** [comment]
<a href="https://github.com/chuckcfs"><img src="https://avatars.githubusercontent.com/u/1383865?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [chuckcfs](https://github.com/chuckcfs)**
_Fri May 29 02:19:47 2015_

----

¿o lo hacemos que sea un parámetro más de búsqueda?

**Comment by codemoe** [comment]
Me parece que este issue ya no es vigente... El dropdown de categorías se genera a partir de todas las categorías y no solo de los documentos de la página visible...

@rodowi Podrías revisar esto?

**Comment by rodowi** [comment]
Confirmado en QA
http://qa.participa.gob.mx/consulta/api/docs?filter=docCategories:13&page=1&per_page=20
