### ISSUE TITLE
No aparece el template original de co-edición + foro en qa

### ISSUE THREAD

**Issue by jipster** [mxabierto/participa#98]
tendríamos que poder ver algo como esto: http://www.gob.mx/participa/docs/manifesto-para-la-gobernanza-de-internet

**Comment by codemoe** [comment]
Ese es el layout por default...

Me parece que esto ya funciona... Así lo veo en mi local...

![template foro](https://cloud.githubusercontent.com/assets/4172905/8857166/63bdaa00-3135-11e5-894c-d21ab621967d.png)

@rodowi @jipster Podrían revisarlo? o mandar un screenshot de cómo se ven los documentos queno usan el layout de cofemer, aga, etc..?

**Comment by rodowi** [comment]
necesitaríamos un redeploy de @urkonn

**Comment by urkonn** [comment]
Está actualizado el código en QA
Si funciona el template 
![selection_047](https://cloud.githubusercontent.com/assets/37691/8881429/5cb2fcf8-3205-11e5-8dd0-5b393c5fbbc0.png)

**Comment by joecohens** [comment]
Se solucionó aquí https://github.com/mxabierto/participa/commit/93bab874b65dd53a6e72378f70dd3776e394d904
